### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by edshkim98** [Cerebras/online-normalization#21]
Thank you very much for providing your code!
As I face an issue with high consumption of GPU memory during training my model, I was planning to use your online-normalization. However, after python -m pip install -e . I get a really long error message.
It seems like a compatibility issue, but can you please have a look what is the cause with my error?
If you would like to see my full error message, please have a look here [error.txt](https://github.com/Cerebras/online-normalization/files/5609969/error.txt), otherwise check the error message below
Thank you

I use:
- CUDA:  10.1
- Pytorch: 1.6.0+cu101
- gcc: 7.5.0
- ubuntu: 18.04
I get the error message as below:

```
    RuntimeError: Error compiling objects for extension
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/edshkim98/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/edshkim98/shkim/online-normalization/online-norm/pytorch/setup.py'"'"'; __file__='"'"'/home/edshkim98/shkim/online-normalization/online-norm/pytorch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

**Comment by vchiley** [comment]
When compiling the code and installing the package, if my env was not perfectly configured, I'd always run into some compiler or install error. I'm not really an expert on compilers/python packages and might not be the best person to ask.

The code / setup / compile  structure is very similar to [detectron2](https://github.com/facebookresearch/detectron2). I'd potentially try looking through their [issues](https://github.com/facebookresearch/detectron2/issues) to see if similar issues happened to someone trying to use that repo.
Please post the fix / workaround you find.
Thank you.

**Comment by vchiley** [comment]
closing stale issue
